### ISSUE TITLE
Index out of bounds (own compilation)

### ISSUE THREAD

**Issue by rwbc** [Mergener/lunachess#2]
Hello Thomas,

I compiled my own binary for Luna, because of my old hardware.
When running from cmd (not tested it with any gui yet because of this)
I get this error always after depth 6.

Any idea what's causing this?

```
LunaChess AB v0.1.0
LUNA_ASSERTS_ON is enabled.
isready
readyok
position startpos
    A B C D E F G H
8 [ r n b q k b n r ]
7 [ p p p p p p p p ]
6 [ . . . . . . . . ]
5 [ . . . . . . . . ]
4 [ . . . . . . . . ]
3 [ . . . . . . . . ]
2 [ P P P P P P P P ]
1 [ R N B Q K B N R ]
Side to move: White
En passant square: --
Zobrist Key: 16973700766173671237

go depth 10
info depth 1 multipv 1 score cp 29 pv e2e4 nodes 41 nps 41000 time 2
info depth 2 multipv 1 score cp 0 pv e2e4 e7e5 nodes 111 nps 27750 time 6
info depth 3 multipv 1 score cp 20 pv e2e4 d7d5 d2d3 nodes 1209 nps 39000 time 36
info depth 4 multipv 1 score cp 1 pv e2e4 d7d5 e4d5 d8d5 nodes 3043 nps 28980 time 141
info depth 5 multipv 1 score cp 16 pv e2e4 e7e5 c2c4 c7c5 d2d3 nodes 27520 nps 38222 time 861
info depth 6 multipv 1 score cp 5 pv e2e4 c7c5 d2d4 c5d4 d1d4 d7d6 nodes 56109 nps 29011 time 2795
[Assertion Failure] In file C:/msys64/home/Guenther Simon/lunachess/src/staticlist.h, function insert, line 26 -- Message:
Index out of bounds.

==================
```

Guenther (RWBC)

**Comment by Mergener** [comment]
Hello Guenther,

Very thankful for the issue report. Actually, the problem was on the assertion itself, since the insert() method should work on indexes that are equal to the size of the list. 

Fixed the assertion and pushed the fixes to the main branch.

**Comment by rwbc** [comment]
Hi again Thomas,

Sorry for the late reply I was a bit low on time the last days.

Thanks for the quick fix and I can confirm that the issue is gone
in my WIN build and I played the first test games with it
in the CUTEChessGUI.

I noticed something else though and file another issue.

Guenther
