### ISSUE TITLE
compile error on Linux : solved

### ISSUE THREAD

**Issue by tissatussa** [Mergener/lunachess#5]
i had an error while compiling your v0.4 source on Linux, but i found the cause : in `tests/staticanalysis/` are two file names with a capital letter : `connectedPawns.cpp` and `passedPawns.cpp` which are referenced in `src/lunatest/testlist.cpp` but there these file names have all lowercase letters .. to make it work on Linux i renamed the two files and then the compilation went well : Linux distinguishes between lowercase and uppercase in file names, Windows does not ..

now the compiled binary runs fine.
[ i'm on Xubuntu 22.04 ]

**Comment by Mergener** [comment]
Thanks for pointing this out! Filenames changed to lowercase to match the rest of the project.

**Comment by tissatussa** [comment]
OK.
i think we should always consider other OS's then Windows : writing code for multi-platform isn't that hard to do ? Such 'bugs' happen often though .. sometimes i can't fix them, but your code is almost perfect :-)
