### ISSUE TITLE
nlohmann/json.hpp not found

### ISSUE THREAD

**Issue by SzotsGabor** [Mergener/lunachess#6]
Hi Thomas,

From under the luna directory I tried to compile Luna using this comman line under Windows 11:

g++ *.cpp ai/*.cpp ai/classiceval/*.cpp -Iai -Iai/classiceval -Inlohmann -std=c++17 -flto -march=native -O3 -oLuna_0.4.0-x64-SzG.exe 2>ki

Still I have error messages like this:

In file included from lunachess.h:12,
                 from lunachess.cpp:1:
openingbook.h:7:10: fatal error: nlohmann/json.hpp: No such file or directory
    7 | #include <nlohmann/json.hpp>
      |          ^~~~~~~~~~~~~~~~~~~

I know nlohmann/json.hpp is not in the package but I have downloaded it.

Can you help?

Gabor Szots
CCRL testing group

**Comment by Mergener** [comment]
Hi Gabor,

I'm not sure I understand your issue entirely, so I'll try to explain what I can.

Luna uses Nlohmann's JSON library to serialize/deserialize evaluation weights. The JSON library is listed as a submodule for Luna's repository, so cloning Luna with `git clone --recurse-submodules https://github.com/mergener/lunachess` will download everything for you. If you didn't clone Luna with the submodules, you can still run `git submodule update --init` (from the project root) and the JSON library should be installed accordingly.

However, from what I understand about your issue, you're trying to compile Luna using g++ directly, without using CMake to generate a Makefile (or a VS solution/similar...). Why is that necessary?

Best regards,
Thomas

**Comment by SzotsGabor** [comment]
I followed your instructions by cloning Luna but it did not help, I still have this:

In file included from ai/aimovefactory.cpp:5:
ai/../pst.h:6:10: fatal error: nlohmann/json.hpp: No such file or directory
    6 | #include <nlohmann/json.hpp>
      |          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from ai/quiescevaluator.h:6,
                 from ai/quiescevaluator.cpp:1:
ai/classiceval/classicevaluator.h:8:10: fatal error: nlohmann/json.hpp: No such file or directory
    8 | #include <nlohmann/json.hpp>
      |          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from ai/search.h:14,
                 from ai/search.cpp:1:
ai/classiceval/classicevaluator.h:8:10: fatal error: nlohmann/json.hpp: No such file or directory
    8 | #include <nlohmann/json.hpp>
      |          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from ai/search.h:14,
                 from ai/timemanager.cpp:3:
ai/classiceval/classicevaluator.h:8:10: fatal error: nlohmann/json.hpp: No such file or directory
    8 | #include <nlohmann/json.hpp>
      |          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from ai/classiceval/classicevaluator.cpp:1:
ai/classiceval/classicevaluator.h:8:10: fatal error: nlohmann/json.hpp: No such file or directory
    8 | #include <nlohmann/json.hpp>
      |          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from ai/classiceval/tuning.h:6,
                 from ai/classiceval/tuning.cpp:1:
ai/classiceval/classicevaluator.h:8:10: fatal error: nlohmann/json.hpp: No such file or directory
    8 | #include <nlohmann/json.hpp>
      |          ^~~~~~~~~~~~~~~~~~~
compilation terminated.

I used to have CMake but I don't understand how to use it and for my simple demands I did not think it was necessary anyway.

I suggest we abandon my issue, it is not particularly important, I just wondered if I can compile a faster exe than the one you provide.

**Comment by SzotsGabor** [comment]
I corrected my command line (g++ *.cpp ai/*.cpp ai/classiceval/*.cpp -Iai -Iai/classiceval -Inlohmann -Iai/nlohmann -std=c++17 -flto -march=native -O3 -oLuna_0.4.0-x64-SzG.exe) and put my nlohmann directory under the ai directory and now I have only one error:

C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../lib/libmingw32.a(lib64_libmingw32_a-crtexewin.o): in function `main':
C:/M/B/src/mingw-w64/mingw-w64-crt/crt/crtexewin.c:67: undefined reference to `WinMain'
collect2.exe: error: ld returned 1 exit status

**Comment by Mergener** [comment]
The problem is that Luna is compiled to a static library, which is then linked to Luna CLI (check the `src/lunacli` subdirectory). LunaCLI is the one that contains the main function (with the UCI main loop...). In this case, you should add `src/lunacli/uci.cpp` and `src/lunacli/main.cpp` to your compile command.

**Comment by Mergener** [comment]
Hi Gabor! 
Were you able to compile Luna?
Is there anything else I can help you with?

**Comment by SzotsGabor** [comment]
No. I installed CMake, created a makefile but it did not help. The strange thing is that 'make' opened a window but did nothing more. I have the feeling that the makefile is for Linux only. I have removed CMake.
Anyway, it is not important, the exe you provided is OK and a tournament for the CCRL blitz list is already inprogress.

**Comment by Mergener** [comment]
OK! For now, I'll mark this issue as closed then. Thanks for reporting your problem! Feel free to open another issue or ask me to reopen this one if necessary.
